"""Budget Analysis Schemas."""

from pydantic import BaseModel, Field


class CostBreakdown(BaseModel):
    """Categorized breakdown of trip expenses."""

    flights: float = Field(0.0, ge=0.0, description="Total flight expense in INR")
    accommodation: float = Field(0.0, ge=0.0, description="Total accommodation expense in INR")
    food: float = Field(0.0, ge=0.0, description="Estimated food expense in INR")
    transport: float = Field(0.0, ge=0.0, description="Estimated local transport expense in INR")
    activities: float = Field(0.0, ge=0.0, description="Estimated sightseeing & activities in INR")
    miscellaneous: float = Field(0.0, ge=0.0, description="Buffer / miscellaneous expenses in INR")


class BudgetAnalysis(BaseModel):
    """Deterministic financial breakdown generated by Budget Agent."""

    estimated_total: float = Field(..., ge=0.0, description="Total estimated travel cost in INR")
    budget_limit: float = Field(..., ge=0.0, description="User budget limit in INR")
    remaining_budget: float = Field(
        ..., description="Remaining budget balance (positive or negative)"
    )
    within_budget: bool = Field(..., description="Flag indicating if total estimate <= limit")
    cost_breakdown: CostBreakdown = Field(..., description="Categorized expense details")
    recommendations: list[str] = Field(
        default_factory=list, description="Budget optimization suggestions"
    )
    status_label: str = Field(
        ..., description="Human readable budget status (e.g. 'Within Budget', 'Over Budget')"
    )
